apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: managed-deploy-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: managed-deploy
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 85